### ISSUE TITLE
Setup Ghost and design functions

### ISSUE THREAD

**Issue by jakapatb** [blockfint/blockfint-landing-2020#29]
## Task
- [x] Setup Ghost and deploy to server `https://blockfint.com/ghost`
- [x] Design get data functions and write it here
- [x] try get data and display to some page (create new one for test is fine) 
### Example
```jsx
getPostById(id: string) // result: Post 
```
---
### Functions
```jsx
import { ghostApi } from '.'
import GhostContentAPI, {
  Params,
  PostOrPage,
  SettingsResponse,
  Pagination,
  PostsOrPages,
  Tag,
  Author
} from '@tryghost/content-api'
interface Dimensions {
  width: number
  height: number
}
interface BrowseResults<T> extends Array<T> {
  meta: { pagination: Pagination }
}
interface NextImage {
  url: string
  dimensions: Dimensions
}
interface GhostPostOrPage extends PostOrPage {
  featureImage?: NextImage | null
  htmlAst?: Node | null
}
interface GhostTag extends Tag {
  featureImage?: NextImage
}

interface GhostTags extends BrowseResults<GhostTag> {
  featureImage?: NextImage
}

const postAndPageSlugOptions: Params = {
  limit: 'all',
  fields: 'slug'
}

const tagAndAuthorFetchOptions: Params = {
  limit: 'all',
  include: 'count.posts'
}
const postAndPageFetchOptions: Params = {
  limit: 'all',
  include: ['tags', 'authors', 'count.posts'],
  order: ['featured DESC', 'published_at DESC']
}

export const getAllPosts = async (props?: { limit: number }): Promise<GhostPostOrPage> => {
  return await ghostApi.posts.browse({ include: 'tags,authors' })
}

export const getSinglePost = async (props?: { id: string }): Promise<GhostPostOrPage> => {
  return await ghostApi.posts.read({ id: `${props}` })
}

// export const getPostsNoCurrent = async (props?: { limit }) => {}
export async function getPostsByTag(slug: string, limit?: number, excludeId?: string): Promise<GhostPostOrPage> {
  const exclude = (excludeId && `+id:-${excludeId}`) || ``
  const posts = await ghostApi.posts.browse({
    ...postAndPageFetchOptions,
    ...(limit && { limit: `${limit}` }),
    filter: `tags.slug:${slug}${exclude}`
  })
  return await posts
}

export async function getTags(): Promise<GhostTags> {
  return await ghostApi.tags.browse(tagAndAuthorFetchOptions)
}
export async function getSingleTag(props?: { limit: number }): Promise<GhostPostOrPage> {
  return await ghostApi.tags.read({ slug: 'Ghost' }, { include: 'count.posts' })
}

export async function getAuthors() {
  return await ghostApi.authors.browse(tagAndAuthorFetchOptions)
}
export async function getSingleAuthor(props?: { limit: number }): Promise<GhostPostOrPage> {
  return await ghostApi.authors.read({ slug: 'blockfint' }, { include: 'count.posts' }) // include can be array for any of these
}
export async function getPostsByAuthor(props?: { limit: number }): Promise<GhostPostOrPage> {
  const post = await ghostApi.posts.browse({ filter: 'primary_author:blockfint' })
  return post
}

export async function getAllPostSlugs(): Promise<string[]> {
  const posts = await ghostApi.posts.browse(postAndPageSlugOptions)
  return posts.map((p) => p.slug)
}

```

--- 

## References
- https://ghost.org/docs/jamstack/next/

**Comment by jakapatb** [comment]
paramaters? @justunee

**Comment by jakapatb** [comment]
in Blog detail, they need tags but getSinglePost not include them

**Comment by justunee** [comment]
set up finish
