### ISSUE TITLE
Create New Typography

### ISSUE THREAD

**Issue by jakapatb** [blockfint/blockfint-landing-2020#31]
## Tasks
- [x] Create new Typgraphy #34
- [x] Override GlobalStyle Typography to Blog section #34 
- [x] Override GlobalStyle Typography to new pages
